# Generated by Django 4.1.2 on 2023-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('huawei', '华为'), ('cisco_ios_telnet', '思科'), ('cisco_ios', '思科'), ('f5_tmsh', 'F5'), ('fortinet', '飞塔'), ('netscaler', 'NS')], max_length=255)),
                ('location', models.CharField(choices=[('XY', '兴议'), ('FD', '福地'), ('SQ', '石桥')], max_length=255)),
                ('role', models.CharField(choices=[('JR', '接入交换机'), ('HX', '核心交换机'), ('HJ', '汇聚交换机'), ('CS', '测试环境'), ('CK', '出口设备'), ('HJ-JR', 'K8s-接入')], max_length=255)),
                ('model', models.CharField(choices=[('HW5700', 'HW5700'), ('HWNE20', 'HWNE20'), ('HW8800', 'HW8800'), ('HW6800', 'HW6800'), ('HW5800', 'HW5800'), ('HW12800', 'HW12800'), ('CS45', 'CS45'), ('CS', 'CS'), ('F5', 'F5'), ('FT', 'FT'), ('NS', 'NS')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('messages', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
