# Generated by Django 4.1.2 on 2023-10-31 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0007_alter_devicedata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='cpu_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='memory_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
