# Generated by Django 4.1.2 on 2024-01-02 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0008_alter_devicedata_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
