# Generated by Django 4.1.2 on 2024-03-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0010_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interface',
        ),
    ]
