# Generated by Django 4.1.2 on 2024-03-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0012_interface_delete_devicedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='index',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='last_phy_uptime',
        ),
    ]
