# Generated by Django 4.1.2 on 2024-03-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0013_remove_interface_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set(),
        ),
    ]
