# Generated by Django 4.1.2 on 2024-03-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0014_alter_interface_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('dev', 'name')},
        ),
    ]
