# Generated by Django 4.1.2 on 2024-03-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0016_alter_interface_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_automation_app.device', verbose_name='关联设备'),
        ),
    ]
