# Generated by Django 4.1.2 on 2024-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0017_alter_interface_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('cabinetNumber', models.CharField(max_length=255)),
                ('JRsw', models.CharField(max_length=255)),
                ('JRdk', models.CharField(max_length=255)),
                ('DKms', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
