# Generated by Django 4.1.2 on 2024-11-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0020_alter_device_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script_path', models.CharField(max_length=255)),
                ('cron_schedule', models.CharField(help_text='Cron format: * * * * *', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
