# Generated by Django 4.1.2 on 2024-11-18 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0021_scheduledtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'verbose_name': 'Scheduled Task', 'verbose_name_plural': 'Scheduled Tasks'},
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='name',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time this task was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The last time this task was updated.'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='cron_schedule',
            field=models.CharField(help_text='Cron expression defining the schedule.', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this task is enabled or not.'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='script_path',
            field=models.CharField(help_text='Path to the script to be executed.', max_length=255),
        ),
    ]
