# Generated by Django 4.1.2 on 2025-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation_app', '0022_alter_scheduledtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(choices=[('XY', '兴议'), ('FD', '福地'), ('XX', '西溪')], max_length=255),
        ),
    ]
